# Generated by Django 2.0.3 on 2018-03-27 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the disease admitted for (e.g stroke, Venous Thromboembolism,etc)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('date_of_resumption', models.DateField(blank=True, null=True, verbose_name='Resumed')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Male/Female', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('summary', models.TextField(help_text='Enter the brief details about the disease/ reason for admission', max_length=1000)),
                ('ClinicID', models.CharField(help_text='Enter the clinic unique ID', max_length=13, verbose_name='CLINICID')),
                ('disease', models.ManyToManyField(help_text='Enter the disease type for the patient', to='patientRecord.Disease')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientRecord.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a particular treatment case', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('discharge_time', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'Admitted'), ('T', 'Treatment'), ('D', 'Discharge')], default='A', help_text='Patient Condition', max_length=1)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientRecord.Patient')),
            ],
            options={
                'ordering': ['discharge_time'],
            },
        ),
    ]
