# Generated by Django 2.0.3 on 2018-03-28 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200)),
                ('number_id', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('date_of_purchase', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
            ],
            options={
                'ordering': ['number_id', 'device_name'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the diagnosis ailments for (e.g stroke, Venous Thromboembolism,etc)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patientRecord.Device'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.ManyToManyField(help_text='Enter the diagnosis type for the patient', to='patientRecord.Diagnosis'),
        ),
    ]
