# Generated by Django 2.0.3 on 2018-03-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientRecord', '0002_auto_20180328_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinstance',
            old_name='id',
            new_name='card_number',
        ),
    ]
